#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.1 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,1,6,7,9,43,65,68&i=15,16,17,39,42&v=17,16,18,39,2 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define OMNIA_SMALL_OGG_OPUS_VORBIS 1
#define OMNIA_OGG_PREBUFFER 60000
#define ARDUINO_ESP32S3_DEV

#define L10N_LANGUAGE			RU
#define I2S_DOUT			17
#define I2S_BCLK			16
#define I2S_LRC			18
#define SDC_CS			39
#define MUTE_PIN			2

#define MICRO_FLAC_MEMORY_PREFER_PSRAM 1

#endif
